
POST http://localhost:3000/auth/register
content-type: application/json

{
  "username":"soo3",
  "password":"qwer",
  "email":"soo3@test.com"
}

###
POST http://localhost:3000/auth/login
content-type: application/json

{

  "password":"qwer",
  "email":"soo2@test.com"
}

### LoginGuard
POST http://localhost:3000/auth/login2
content-type: application/json 

{
  "password":"qwer",
  "email":"soo2@test.com"
}

### Guard 테스트
GET http://localhost:3000/auth/test-guard

### 로그인3
POST http://localhost:3000/auth/login3
content-type: application/json 

{
  "email":"soo3@test.com",
  "password":"qwer"
}

### 인증이 성공 하는지 테스트
GET http://localhost:3000/auth/test-guard2